### ISSUE TITLE
Ingest @ 5,000 rows/batch causes Docker engine to crash

### ISSUE THREAD

**Issue by idbjorh** [IBMProjectEventStore/EventStore-DeveloperEdition#2]
I'm using the EventStore demo on macOS Sierra, with the latest build of Docker (17.03.1-ce-mac12).  I have configured Docker to have 8Gb RAM and 4 CPU cores.

When running the ingest process in `retail_demo.ipynb`, if I leave *Rows per batch* at the default value (1,000), ingest will run fine for extended periods.

However, if I increase *Rows per batch* to 5,000, the ingest process causes Docker to crash – not just one container, but the entire Docker engine.  In my case, it took just over 19 seconds (@ ~120k rows/s) before Docker crashed.

I was running `docker stats` while performing the ingest, to see if it was a memory issue, but just before the engine crashed, aggregate memory usage of the 4 containers totaled 5.16Gb - 65%.

**Comment by MGupta2017** [comment]
We are looking into this and have reproduced a container crash with the same steps. Expect to have the fix in next refresh.
